// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

// Version defines model for Version.
type Version struct {
	// Api API major version
	Api     int    `json:"api"`
	Version string `json:"version"`
}
